version: '3.8'

services:

  testapp:
    build: .
    image: testapp
    command: uvicorn tests.app:app --host 0.0.0.0 --port 8000

  testclient:
    image: testapp
    command: pytest
    depends_on:
      - testapp
